# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Frugal Design"
#googleAnalytics = "UA-35321282-1"


# navigation
[menu]

  [[menu.main]]
  name = "Home"
  URL = "/#hero"
  identifier = "home"
  weight = 1

  [[menu.main]]
  name = "About"
  URL = "#about"
  identifier = "about"
  weight = 2

  [[menu.main]]
  name = "Clients"
  URL = "#client"
  identifier = "client"
  weight = 3
  
  [[menu.main]]
  name = "Services"
  url = "#services"
  identifier = "planos"
  weight = 4

  [[menu.main]]
  name = "Pricing"
  identifier = "pricing"
  url = "#pricing"
  weight = 5

  [[menu.main]]
  name = "Reviews"
  URL = "#reviews"
  identifier = "reviews"
  weight = 6


[params]

  logo = "img/logo_Frugal_full.svg"
  # To provide some metadata for search engines feel free to add a few information about you and your website.
  name = "Frugal Consultancy &amp; Design Limited"
  description = "Cost-effective freelance engineering design using 3D CAD &amp; CAE modelling."
  email = ""

[params.author]
  name= "Thomas H."
  image= "img/HireMe_ProfilePic.jpg"
  position= "Chartered Engineer"
  expert= "3D CAD / CAE Expert" 
  rating= "5"


  # Hero 
[params.hero]
    title = "frugal"
    subtitle = "adjective  | ˈfrü-gəl"
	  text = "Cost-effective freelance engineering design using 3D CAD &amp; CAE modelling"
    image = "img/bg_Hull.jpg"

    
  # About 
[params.about]
    title = "About"
	  text = "Frugal Consultancy &amp; Design is a Yorkshire based company established in 2012 by Thomas Hartley to offer his freelance design engineering services. Tom set out to provide cost-effective, flexible, yet reliable design services to clients for whom traditional engineering consultancy hadn’t really delivered good value in the past."
    textBottom = "Tom is a Chartered Mechanical Engineer, qualified Product Design &amp; Manufacturing Engineer, and a highly skilled 3D modeller. As a member of both the Institute of Mechanical Engineering and the Institute of Engineering Designers, he works to the institutions' professional standards, as well as the ethical &amp; sustainability principles overseen by the Engineering Council and Royal Academy of Engineering."
    image = "img/Header_Hull.jpg"
    buttonText = "View profile on Linkedin"
    buttonUrl = "https://www.linkedin.com/in/tphartley/"

[[params.about.imageLists]]
url= "img/About_IMECHE.png"
alt= "im1"
link= "https://www.imeche.org/"

[[params.about.imageLists]]
url= "img/About_IED.png"
alt= "im1"
link= "https://www.institution-engineering-designers.org.uk/"

[[params.about.imageLists]]
url= "img/About_RAE.png"
alt= "im1"
link= "https://www.raeng.org.uk/"

[[params.about.imageLists]]
url= "img/About_EC.png"
alt= "im1"
link= "https://www.engc.org.uk/"

  # Clients 
[params.clients]
    title = "Clients"
	  subTitle = "Frugal provide flexible &amp; cost-effective freelance engineering design support for:"  

[[params.clients.boxLists]]
icon= "img/Clients_M.svg"
title= "Manufacturers"
url= "/"
text= "Providing digital innovation to help you improve your existing designs and develop new products."


[[params.clients.boxLists]]
icon= "img/Clients_DB.svg"
title= "D&amp;B Contractors"
url= "/"
text= "Building and managing 3D coordination models to help you win bids &amp; improve your contract delivery."


[[params.clients.boxLists]]
icon= "img/Clients_FM.svg"
title= "Facility Managers"
url= "/"
text= "Delivering facility &amp; project coordination models, to help you improve your workflows &amp; productivity."


[[params.clients.belowSection]]
title= ""
image= "img/Client_Aims.png"
btnText= "View Portfolio on Upwork"
btnUrl= "https://upwork.com/fl/thomash1089"
btnKlass = "btn-orange"



[[params.clients.belowSection.lists]]
 text = " To modernize, innovate, and become more sustainable."
[[params.clients.belowSection.lists]]
 text = " To minimize waste and become leaner than your competitors."
[[params.clients.belowSection.lists]]
 text = "To maximize value-creation and your return-on-investment."


 
[[params.clients.belowSection]]
title= ""
image= "img/Client_Reqs.png"
btnText= "Book a call to discuss your requirements"
btnUrl= "https://calendly.com/tom-frugaldesign/discuss"
btnKlass = "btn-green"

[[params.clients.belowSection.lists]]
text = " On a fixed-price & fixed-scope basis."
[[params.clients.belowSection.lists]]
text = "In an open, honest, collaborative & mutually respectful way."
[[params.clients.belowSection.lists]]
text = " Predominantly from our well-equipped East Yorkshire based office."

# SERVICES

[params.services]
    title = "Services"
	  subTitle = "Frugal offer pre-packaged or bespoke freelance services built around three core specialisms:" 


[[params.services.boxLists]]
image= "img/Services_3DModelling.svg"
title= "3D CAD &amp; CAE Modelling"
text= "For clear &amp; accurate embodiment, quantification, testing &amp; optimisation of your ideas, rapidly and at minimal cost."

[[params.services.boxLists]]
image= "img/Services_EngDesign.svg"
title= "Engineering Design"
text= "Process-driven development of elegant, imaginative &amp; technically viable solutions that best suit your specific constraints."

[[params.services.boxLists]]
image= "img/Services_Coordination.svg"
title= "3D Coordination Modelling"
text= "Comprehensive &amp; evidence-based models that help you plan, manage, monitor &amp; coordinate your projects."

[[params.services.belowSection]]
title= ""
image= "img/Services_Skills.png"
btnText= "View Portfolio on Upwork"
btnUrl= "https://upwork.com/fl/thomash1089"
btnKlass = "btn-orange"

[[params.services.belowSection.lists]]
text = " Product Design"
[[params.services.belowSection.lists]]
text = " Mechanical Design"
[[params.services.belowSection.lists]]
text = " Static Structural Design"
[[params.services.belowSection.lists]]
text = " Site / Plant Layouts"
[[params.services.belowSection.lists]]
text = " Construction Planning / Sequencing"

[[params.services.belowSection]]
title= ""
image= "img/Services_Experience.png"
btnText= "Book a call to discuss your requirements"
btnUrl= "https://calendly.com/tom-frugaldesign/discuss"
btnKlass = "btn-green"

[[params.services.belowSection.lists]]
text = " Nuclear Decommissioning"
[[params.services.belowSection.lists]]
text = " Green & Sustainable Products"
[[params.services.belowSection.lists]]
text = " Bridges & Civil Infrastructure"
[[params.services.belowSection.lists]]
text = " Energy & Renewables"
[[params.services.belowSection.lists]]
text = " Process & Power"


# Pricing

[params.pricing]
title = "PRICING"
subTitle = "To match your budget, whether you want something rough & ready, polished & pretty, or fully designed & detailed:" 

[[params.pricing.list]]
text= ""
image= "img/Pricing_Fiverr.jpg"
alt =""
buttonText = "Browse prices on Fiverr"
buttonUrl= "https://www.fiverr.com/tphartley"
buttonKlass= "btn-red"

[[params.pricing.list]]
text= ""
image= "img/Pricing_Direct.jpg"
alt =""
buttonText = "Request a quote direct (for better rates!)"
buttonUrl= "https://calendly.com/tom-frugaldesign/quote"
buttonKlass= "btn-green"



# Testimonials
[params.testimonialsBackground]
 image= "img/bg_Sheffield.jpg"

[[params.testimonials]]
name = "Programme Manager"
position= "Nuclear Plant, Cheshire"
image= "img/Clients_FM.svg"
text= "Tom developed a full 3D building &amp; process systems model that enabled comprehensive design construction &amp; maintenance reviews to be carried out early in our project's life cycle. The model really shone a light on things, highlighted risks we hadn’t even seen, and allowed us to hold our sub-contractors to account with much less effort. We were able to use the model for many other stakeholder engagements and briefing sessions as well, which were always well-received &amp; very productive."


[[params.testimonials]]
name = "Design Director"
position= "D&amp;B Contractor, Sheffield"
image= "img/Clients_DB.svg"
text= "Tom is able to consume &amp; make sense of huge amounts of information in a short space of time, always keeps us up to date, and regularly delivers content we can use directly in our proposals. He's helped us impress clients &amp; win work on a diverse range of bids over the years... bridge access &amp; maintenance; bulk handling &amp; storage; hazardous waste processing; heat-recovery systems. Once his work even helped us win a very long-shot & lucrative place on a huge long-term frame-work agreement!"


[[params.testimonials]]
name = "Managing Director"
position= "Loading Equipment Fabricator, Chesterfield"
image= "img/Clients_M.svg"
text= "Tom developed a baseline information model on our biggest selling product, which allowed us to view the product in ways we’d never thought about before. He helped us brainstorm all kinds of new ideas, which he worked up into several design models for baseline comparisons. Through many small design &amp; production changes, we were able to eliminate at least 20% of the product’s overall manufacturing cost, without affecting functionality or end-user experience at all!"


[[params.testimonials]]
name = "Engineering Director"
position= "Civil / Structures Contractor, Hull"
image= "img/Clients_DB.svg"
text= "The project has come on leaps and bounds and althouth the model represents great value in its own right, it’s the immeasurable other things that added the real value, like how he engaged our people &amp; teased out their real needs &amp; preferences very early on in the project."


[params.footer]
copyright = " Frugal Consultancy &amp; Design Ltd.<br>Registered in England &amp; Wales | Company No. 08241771 | VAT No. GB 166 493 575"

[params.button1]
caption = "Hire me on Fiverr"
url= "https://fiverr.com/tphartley"

[params.button2]
caption = "Hire me on Upwork"
url= "https://upwork.com/fl/thomash1089"

[params.button3]
caption = "Hire me Direct"
url= "https://calendly.com/tom-frugaldesign/hire"