# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Frugal Design"
#googleAnalytics = "UA-35321282-1"


# navigation
[menu]

  [[menu.main]]
  name = "Home"
  URL = "/#hero"
  identifier = "home"
  weight = 1

  [[menu.main]]
  name = "About"
  URL = "#about"
  identifier = "about"
  weight = 2

  [[menu.main]]
  name = "Clients"
  URL = "#client"
  identifier = "client"
  weight = 3
  
  [[menu.main]]
  name = "Services"
  url = "#services"
  identifier = "planos"
  weight = 4

  [[menu.main]]
  name = "Pricing"
  identifier = "pricing"
  url = "#pricing"
  weight = 5

  [[menu.main]]
  name = "Reviews"
  URL = "#reviews"
  identifier = "reviews"
  weight = 6


[params]

  logo = "img/logo_Frugal_full.svg"
  # To provide some metadata for search engines feel free to add a few information about you and your website.
  name = "Frugal Consultancy & Design Limited"
  description = "Frugal is a Digital Engineering Design house that works smart to reduce & eliminate wastes, risks & complications from your projects."
  email = ""

[params.author]
  name= "Thomas H."
  image= "img/HireMe_ProfilePic.jpg"
  position= "Chartered Design  Engineer"
  expert= "3D CAD / CAE Expert" 
  rating= "5"


  # Hero 
[params.hero]
    title = "frugal"
    subtitle = "adjective  | ˈfrü-gəl"
	  text = "Cost-effective freelance engineering design using 3D CAD & CAE modelling"
    image = "img/banner.jpg"

    
  # About 
[params.about]
    title = "About Frugal"
	  text = "Frugal Consultancy &amp; Design is a Yorkshire based company that was established in 2012 by Thomas Hartley, through which to offer freelance design engineering services. Tom set out to provide a cost-effective, flexible yet reliable design service to clients for whom traditional engineering consultancy hadn’t really delivered good value in the past."
    textBottom = "Tom is a Chartered Mechanical Engineer, qualified Product Design & Manufacturing Engineer, and a highly skilled 3D modeller. As a member of both the Institute of Mechanical Engineering and the Institute of Engineering Designers, he works to their professional standards and upholds the ethical principles published by the Engineering Council and Royal Academy of Engineering."
    image = "img/banner.jpg"
    buttonText = "View my profile on Linkedin (1)"
    buttonUrl = "https://www.linkedin.com/in/tphartley/"

[[params.about.imageLists]]
url= "img/img1.png"
alt= "im1"
link= "https://www.imeche.org/"
[[params.about.imageLists]]
url= "img/img2.png"
alt= "im1"
link= "https://www.institution-engineering-designers.org.uk/"
[[params.about.imageLists]]
url= "img/img3.png"
alt= "im1"
link= "https://www.raeng.org.uk/"
[[params.about.imageLists]]
url= "img/img4.png"
alt= "im1"
link= "https://www.engc.org.uk/"

  # Clients 
[params.clients]
    title = "Our Clients"
	  subTitle = "We offer flexible &amp; cost-effective freelance engineering design support to:"  

[[params.clients.boxLists]]
icon= "img/Clients_FM.svg"
title= "Manufacturers"
url= "/"
text= "We can provide digital design innovation to develop new products, or improve your existing ones."


[[params.clients.boxLists]]
icon= "img/Clients_DB.svg"
title= "D&amp;B Contractors"
url= "/"
text= "We can build and manage 3D coordination models to win bids &amp; improve contract delivery."


[[params.clients.boxLists]]
icon= "img/Clients_M.svg"
title= "Facility Managers"
url= "/"
text= "We can deliver facility &amp; project coordination models, for more efficient &amp; reliable facilities management."


[[params.clients.belowSection]]
title= "Our aim is to help you:"
image= "img/Client_Aims.jpg"
btnText= "View our portfolio on Upwork (1)"
btnUrl= "https://upwork.com/fl/thomash1089"
btnKlass = "btn-orange"



[[params.clients.belowSection.lists]]
 text = " To modernize, innovate, and become more sustainable;"
[[params.clients.belowSection.lists]]
 text = " To minimize waste and become leaner than your competitors;"
[[params.clients.belowSection.lists]]
 text = "To maximize value-creation and your return-on-investment in us."


 
[[params.clients.belowSection]]
title= "We’re able to do this best when we work:"
image= "img/Client_Reqs.jpg"
btnText= "Book a call to find out if we're a good fit! (1)"
btnUrl= "https://calendly.com/tom-frugaldesign/discovery"
btnKlass = "btn-green"

[[params.clients.belowSection.lists]]
 text = " Mostly from our own well-equipped office in Hull;"
[[params.clients.belowSection.lists]]
 text = " On a fixed-scope / fixed-price basis;"

[[params.clients.belowSection.lists]]
 text = "In an open, honest, collaborative & mutually respectful way."

# SERVICES

[params.services]
    title = "Services"
	  subTitle = "We offer a range of pre-packaged and bespoke freelance services built on our core specialisms of:" 


[[params.services.boxLists]]
image= "img/Services_3DModelling.svg"
title= "3D CAD &amp; CAE Modelling"
text= "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor."

[[params.services.boxLists]]
image= "img/Services_EngDesign.svg"
title= "Engineering Design"
text= "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor."

[[params.services.boxLists]]
image= "img/Services_Coordination.svg"
title= "3D Coordination Modelling"
text= "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor."

[[params.services.belowSection]]
title= "Skills:"
image= "img/Services_Skills.jpg"
btnText= "View our portfolio on Upwork (2)"
btnUrl= "https://upwork.com/fl/thomash1089"
btnKlass = "btn-orange"

[[params.services.belowSection.lists]]
text = " Mechanical & Static Structural Design"
[[params.services.belowSection.lists]]
text = " Plant, Site & Construction Design"
[[params.services.belowSection.lists]]
text = " Product Design"

[[params.services.belowSection]]
title= "Experience:"
image= "img/Services_Experience.jpg"
btnText= "Book a call to find out if we're a good fit! (2)"
btnUrl= "https://calendly.com/tom-frugaldesign/discovery"
btnKlass = "btn-green"

[[params.services.belowSection.lists]]
 text = " Lorem ipsum dolor sit amet consectetuer adipiscing elit"
[[params.services.belowSection.lists]]
 text = " Lorem ipsum dolor sit amet consectetuer adipiscing elit"
[[params.services.belowSection.lists]]
 text = " Lorem ipsum dolor sit amet consectetuer adipiscing elit"

# Pricing

[params.pricing]
title = "PRICING"
subTitle = "We're comfortable adapting to suit the needs & budget of your project. Whether you want rough & ready, polished & pretty or fully designed & detailed, we'll be able to help." 

[[params.pricing.list]]
text= "We have a range of pre-packaged, fixed-price offers that provide a fair outline of our pricing levels and the kind of output you can expect. These might fit your needs exactly, or can be tweaked & adjusted if they’re almost-but-not-quite what you need."
image= "img/Pricing_Fiverr.jpg"
alt =""
buttonText = "View pre-packaged projects on Fiverr (1)"
buttonUrl= "https://www.fiverr.com/tphartley"
buttonKlass= "btn-red"

[[params.pricing.list]]
text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat ex ea commodo consequat."
image= "img/Pricing_Direct.jpg"
alt =""
buttonText = "Request a direct quote for best rates (1)"
buttonUrl= "https://calendly.com/tom-frugaldesign/quote-me"
buttonKlass= "btn-green"



# Testimonials
[params.testimonialsBackground]
 image= "img/testimonials-bg.jpg"

[[params.testimonials]]
name = "Nuclear Plant, Cheshire"
position= "Programme Manager"
image= "img/Services_3DModelling.svg"
text= "Tom developed a full 3D building &amp; process systems model that enabled comprehensive design construction &amp; maintenance reviews to be carried out early in the project life-cycle. It really shone a light on things, highlighting risks we hadn’t even seen, and allowed us to hold our sub-contractors to account with much less effort. We were able to use the model for many other stakeholder engagements and briefing sessions too, which were always well-received &amp; productive."


[[params.testimonials]]
name = "D&amp;B Contractor, Hull"
position= "Designer"
image= "img/Services_Coordination.svg"
text= "Frugal are able to consume &amp; make sense of huge amounts of information in a short space of time, always coming back to us with content we can use directly in our proposals. They’ve helped us impress clients &amp; win work on such a diverse range of bids over the years: bridge access &amp; maintenance; bulk handling &amp; storage; hazardous waste processing; heat-recovery systems; even a lucrative (and long-shot) place on a huge frame-work contract at one point!"


[[params.testimonials]]
name = "Loading Equipment Fabricator, Chesterfield"
position= "Managing Director"
image= "img/Services_EngDesign.svg"
text= "Tom developed a baseline information model on our biggest selling product, which allowed us to view it in ways we’d never thought about before. He helped us brainstorm all kinds of new ideas, which he worked up into several design models for comparison with the baseline. Through many small design &amp; production changes, we were able to eliminate at least 20% of the product’s overall manufacturing cost, without affecting the end-user experience at all!"

[params.footer]
copyright = " Frugal Consultancy &amp; Design Ltd.<br>Registered in England &amp; Wales | Company No. 08241771 | VAT No. GB 166 493 575"

[params.button1]
caption = "Hire me on Fiverr"
url= "https://fiverr.com/tphartley"

[params.button2]
caption = "Hire me on Upwork"
url= "https://upwork.com/fl/thomash1089"

[params.button3]
caption = "Hire me Direct"
url= "http://calendly.com/tom-frugaldesign/hire-me"